spring:
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  include: /lobby/api/v1**
  exclude:
    - /actuator/**
    - /swagger-ui/**
  write:
    chunk-size: 1000

api:
  player-service:
    scheme: https
    host: g4s9pjylt0.api.quickmocker.com
    port:
    path: player-service/api/v1/players
  games-repository:
    scheme: https
    host: g4s9pjylt0.api.quickmocker.com
    port:
    path: games-repository/api/v1/games